### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by Retnirps** [Retnirps/Veather240#1]
=== Changes in model.js ===

coordinates -> latitude and longitude
wind -> windDirection and windSpeed

![image](https://user-images.githubusercontent.com/44922573/114281140-60a85e80-9a45-11eb-9099-378e52fc35f0.png)
![image](https://user-images.githubusercontent.com/44922573/114281095-0c9d7a00-9a45-11eb-9649-2c3cafdc3f93.png)

=== Changes in presenter.js ===

checking for empty edit text added

![image](https://user-images.githubusercontent.com/44922573/114281261-14a9e980-9a46-11eb-9679-70520e616e61.png)

updateMainCityCard(city) -> updateMainCityCard(latitude, longitude)

loading added to main card

![image](https://user-images.githubusercontent.com/44922573/114281290-3d31e380-9a46-11eb-893f-d19d1cc9ca0e.png)

Duplicates in functions fillCityWindowTemplate(city) and fillMainCardTemplate(city) removed by creating a new function fillValues(template, city)

![image](https://user-images.githubusercontent.com/44922573/114281324-5fc3fc80-9a46-11eb-9452-2a6d5eb37656.png)
 
=== Changes in script.js ===

default city = "Saint Petersburg" to 
![image](https://user-images.githubusercontent.com/44922573/114281456-1fb14980-9a47-11eb-9232-438bcb5a8267.png)

main card updated by coordinates
![image](https://user-images.githubusercontent.com/44922573/114281370-b29db400-9a46-11eb-8d26-4023cd13d9a3.png)

**Comment by BakasaRus** [comment]
- [x] В `createCityWeather` нужно уменьшить вложенность кода;
- [x] Методы, получающие погоду, различаются по логике: где-то возвращается статус с ошибкой, где-то алерт кидается. Нужно поправить (мб везде ошибку возвращать);
- [x] Карточки погоды грузятся не в том порядке, в котором они хранятся в локальном хранилище.
